import Foundation

enum AnalyticsEventName: String, CaseIterable, Codable {
    case appOpened = "app_opened"
    case sessionStarted = "session_started"
    case onboardingStarted = "onboarding_started"
    case onboardingStepCompleted = "onboarding_step_completed"
    case originFamilySelected = "origin_family_selected"
    case identitySelected = "identity_selected"
    case avatarCreated = "avatar_created"
    case starterVowRecommended = "starter_vow_recommended"
    case starterVowAccepted = "starter_vow_accepted"
    case starterVowEdited = "starter_vow_edited"
    case onboardingCompleted = "onboarding_completed"
    case firstMagicalMomentViewed = "first_magical_moment_viewed"
    case vowCompleted = "vow_completed"
    case dayCompletedFirstVow = "day_completed_first_vow"
    case resonanceAwarded = "resonance_awarded"
    case goldAwarded = "gold_awarded"
    case districtProgressed = "district_progressed"
    case worldSceneOpened = "world_scene_opened"
    case npcInteractionStarted = "npc_interaction_started"
    case npcDialogueCompleted = "npc_dialogue_completed"
    case chapterStarted = "chapter_started"
    case chapterMilestoneReached = "chapter_milestone_reached"
    case chapterCompleted = "chapter_completed"
    case itemAwarded = "item_awarded"
    case shopOpened = "shop_opened"
    case shopPurchaseCompleted = "shop_purchase_completed"
    case widgetViewed = "widget_viewed"
    case widgetTapped = "widget_tapped"
    case liveActivityStarted = "live_activity_started"
    case liveActivityTapped = "live_activity_tapped"
    case shortcutInvoked = "shortcut_invoked"
    case notificationPromptViewed = "notification_prompt_viewed"
    case notificationPermissionResult = "notification_permission_result"
    case notificationSent = "notification_sent"
    case notificationOpened = "notification_opened"
    case healthkitPromptViewed = "healthkit_prompt_viewed"
    case healthkitPermissionResult = "healthkit_permission_result"
    case verifiedCompletionImported = "verified_completion_imported"
    case paywallViewed = "paywall_viewed"
    case trialStarted = "trial_started"
    case purchaseStarted = "purchase_started"
    case purchaseCompleted = "purchase_completed"
    case purchaseFailed = "purchase_failed"
    case subscriptionRestored = "subscription_restored"
    case subscriptionRenewed = "subscription_renewed"
    case subscriptionCanceled = "subscription_canceled"
    case subscriptionExpired = "subscription_expired"
}

struct AnalyticsEvent: Equatable {
    let name: AnalyticsEventName
    let surface: String
    let properties: [String: String]
}
